### ISSUE TITLE
Failure on Codeforces Round #632 (Div. 2)

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-template-generator#3]
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr"><a href="https://twitter.com/kimiyuki_u?ref_src=twsrc%5Etfw">@kimiyuki_u</a><br>online-judge-template-generatorのバグ(?)報告です<a href="https://t.co/IEQ0JSwbSK">https://t.co/IEQ0JSwbSK</a><br>に使用したところ、Dまでは問題無くディレクトリの作成/テンプレートファイルの生成/テストケースのDLが行えましたが、E以降ではエラーが発生するようです</p>&mdash; こるとん (@kyort0n) <a href="https://twitter.com/kyort0n/status/1247921611652485125?ref_src=twsrc%5Etfw">April 8, 2020</a></blockquote>

https://codeforces.com/contest/1333
https://codeforces.com/contest/1333/problem/E

**Comment by kmyk** [comment]
``` python
$ oj-template https://codeforces.com/contest/1333/problem/E
INFO:onlinejudge._implementation.logging:[x] load cookie from: /home/user/.local/share/online-judge-tools/cookie.jar
INFO:onlinejudge._implementation.logging:[x] problem recognized: CodeforcesProblem.from_url('https://codeforces.com/contest/1333/problem/E'): https://codeforces.com/contest/1333/problem/E
INFO:onlinejudge._implementation.logging:[x] GET: https://codeforces.com/contest/1333/problem/E
INFO:onlinejudge._implementation.logging:[x] 200 OK
INFO:onlinejudge._implementation.logging:[x] save cookie to: /home/user/.local/share/online-judge-tools/cookie.jar
ERROR:onlinejudge_template.analyzer.combined:input analyzer failed: 
ERROR:onlinejudge_template.analyzer.combined:output analyzer failed: 
Traceback (most recent call last):
  File "/home/user/.local/bin/oj-template", line 11, in <module>
    load_entry_point('online-judge-template-generator', 'console_scripts', 'oj-template')()
  File "/home/user/GitHub/online-judge-template-generator/onlinejudge_template/main.py", line 36, in main
    analyzed = onlinejudge_template.analyzer.combined.run(resources)
  File "/home/user/GitHub/online-judge-template-generator/onlinejudge_template/analyzer/combined.py", line 66, in run
    output_format = onlinejudge_template.analyzer.simple_patterns.guess_format_with_pattern_matching(instances=output_samples)
  File "/home/user/GitHub/online-judge-template-generator/onlinejudge_template/analyzer/simple_patterns.py", line 299, in guess_format_with_pattern_matching
    match_format(pattern, data.decode(), variables=variables)
  File "/home/user/GitHub/online-judge-template-generator/onlinejudge_template/analyzer/match.py", line 145, in match_format
    _match_format_dfs(node, tokens, variables=variables, values=values)
  File "/home/user/GitHub/online-judge-template-generator/onlinejudge_template/analyzer/match.py", line 112, in _match_format_dfs
    _match_format_dfs(item, tokens, variables=variables, values=values)
  File "/home/user/GitHub/online-judge-template-generator/onlinejudge_template/analyzer/match.py", line 121, in _match_format_dfs
    del values[node.name]
KeyError: 'i'
```
