### ISSUE TITLE
oj-template fails with "Cant locate template for uri 'template.cpp'"

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-template-generator#4]
``` console
$ pip3 show online-judge-template-generator | grep Version
Version: 4.0.1

$ oj-template https://codeforces.com/contest/1333/problem/D
INFO:onlinejudge._implementation.logging:[x] load cookie from: /home/user/.local/share/online-judge-tools/cookie.jar
INFO:onlinejudge._implementation.logging:[x] problem recognized: CodeforcesProblem.from_url('https://codeforces.com/contest/1333/problem/D'): https://codeforces.com/contest/1333/problem/D
INFO:onlinejudge._implementation.logging:[x] GET: https://codeforces.com/contest/1333/problem/D
INFO:onlinejudge._implementation.logging:[x] 200 OK
INFO:onlinejudge._implementation.logging:[x] save cookie to: /home/user/.local/share/online-judge-tools/cookie.jar
ERROR:onlinejudge_template.analyzer.combined:input analyzer failed: 
ERROR:onlinejudge_template.analyzer.combined:output analyzer failed: 
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/mako/lookup.py", line 249, in get_template
    return self._check(uri, self._collection[uri])
KeyError: 'template.cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/oj-template", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge_template/main.py", line 39, in main
    code = onlinejudge_template.generator.run(analyzed, template_file=parsed.template)
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge_template/generator/__init__.py", line 25, in run
    template = lookup.get_template(template_file)
  File "/home/user/.local/lib/python3.6/site-packages/mako/lookup.py", line 263, in get_template
    "Cant locate template for uri %r" % uri
mako.exceptions.TopLevelLookupException: Cant locate template for uri 'template.cpp'
```

**Comment by kmyk** [comment]
fixed by https://github.com/kmyk/online-judge-template-generator/commit/4b5c4a6d4283edad7afa898fdaa121094a33a6a6
